export const CFR_CITATIONS: Record<string, string> = {
  "200.318": "General procurement standards: Non-federal entities must use their own documented procurement procedures which reflect applicable state, local, and tribal laws and regulations.",
  "200.400": "Policy guide: Cost principles establish standards for determining which costs are allowable charges to federal awards.",
  "200.403": "Factors affecting allowability: Costs must be necessary and reasonable, allocable, authorized, consistently treated, and adequately documented.",
  "200.405": "Allocable costs: A cost is allocable to a particular federal award if the goods or services involved are chargeable in accordance with relative benefits received.",
  "200.413": "Direct costs: Costs that can be identified specifically with a particular final cost objective (i.e., a specific federal award) are direct costs.",
  "200.414": "Indirect (F&A) costs: Facilities and administrative costs that benefit more than one cost objective. De minimis rate may be used in lieu of negotiated rate.",
  "200.420": "Considerations for selected items of cost: Rules for 56 specific cost items, determining whether each is allowable, allowable with conditions, or unallowable.",
  "200.421": "Advertising and public relations: Allowable for recruitment, procurement, disposal of surplus, and required program outreach; unallowable for promotional or lobbying purposes.",
  "200.425": "Audit services: Costs of audits required under the Single Audit Act are allowable charges.",
  "200.426": "Bad debts: Losses from uncollectible accounts and related collection costs are unallowable.",
  "200.428": "Collections of improper payments: Costs incurred to recover improper payments are allowable.",
  "200.430": "Compensation — personal services: Charges for salaries and wages must be based on records that accurately reflect the work performed.",
  "200.431": "Compensation — fringe benefits: Allowable if the cost is reasonable, required by law, or established under written policies.",
  "200.432": "Conferences: Costs of meetings and conferences where the primary purpose is the dissemination of technical information are generally allowable.",
  "200.433": "Contingency provisions: Contributions to contingency reserves or provisions for unforeseen events are generally unallowable.",
  "200.434": "Contributions and donations: Costs of contributions and donations from the non-federal entity to other organizations are unallowable.",
  "200.436": "Depreciation: Depreciation on buildings, capital improvements, and equipment is allowable with conditions.",
  "200.437": "Employee health and welfare costs: Costs of health or welfare services for employees are allowable with conditions.",
  "200.438": "Entertainment costs: Costs of amusement, social activities, and related items are unallowable except where specifically approved.",
  "200.439": "Equipment and other capital expenditures: Capital expenditures for general purpose equipment, buildings, and land improvements require prior approval.",
  "200.440": "Exchange rates: Cost increases for fluctuations in exchange rates are allowable costs, subject to prior approval requirements.",
  "200.441": "Fines, penalties, damages, and other settlements: Costs from violations of law or failure to comply with federal, state, local, or tribal laws are unallowable.",
  "200.442": "Fund raising and investment management costs: Costs of organized fund raising are unallowable.",
  "200.443": "Gains and losses on disposition of depreciable assets: Gains or losses from disposition of depreciable property must be properly allocated.",
  "200.444": "General costs of government: Costs of general government are unallowable for state, local, and Indian tribal governments.",
  "200.445": "Goods or services for personal use: Costs for goods or services for personal use of employees are unallowable.",
  "200.447": "Insurance and indemnification: Costs of insurance required or approved are allowable.",
  "200.448": "Intellectual property: Costs for securing patents, copyrights, or rights in data are allowable with conditions.",
  "200.449": "Interest: Financing costs for equipment, buildings, or land are generally allowable under conditions for governmental units.",
  "200.450": "Lobbying: Costs associated with lobbying activities are unallowable.",
  "200.451": "Losses on other awards or contracts: Any excess costs over income on other awards are unallowable.",
  "200.452": "Maintenance and repair costs: Costs for maintenance and repair of buildings and equipment are allowable.",
  "200.453": "Materials and supplies costs: Costs incurred for materials, supplies, and fabricated parts are allowable.",
  "200.454": "Memberships, subscriptions, and professional activity costs: Costs of professional/technical memberships are allowable.",
  "200.455": "Organization costs: Costs such as incorporation fees and costs of reorganization are unallowable except with prior approval.",
  "200.456": "Participant support costs: Direct costs for participants (stipends, travel, registration) are allowable with agency approval.",
  "200.458": "Pre-award costs: Costs incurred prior to the effective date of the federal award may be allowable with agency approval.",
  "200.459": "Professional service costs: Costs of professional and consultant services are allowable when reasonable and necessary.",
  "200.460": "Proposal costs: Costs of preparing proposals for federal awards are allowable as indirect costs.",
  "200.461": "Publication and printing costs: Costs of publication, including electronic media, are allowable.",
  "200.462": "Rearrangement and reconversion costs: Costs of ordinary or normal rearrangement and alteration of facilities are allowable.",
  "200.463": "Recruiting costs: Costs of recruitment are allowable to the extent that costs are incurred pursuant to the non-federal entity's standard policies.",
  "200.464": "Relocation costs of employees: Costs of relocating employees are allowable with conditions.",
  "200.465": "Rental costs of real property and equipment: Rental costs are allowable to the extent they are reasonable and not excessive.",
  "200.467": "Selling and marketing costs: Costs of selling and marketing goods or services are generally unallowable.",
  "200.468": "Specialized service facilities: Costs of services provided by highly complex or specialized facilities are allowable with conditions.",
  "200.469": "Student activity costs: Costs for intramural activities, student publications, or student organizations are unallowable.",
  "200.470": "Taxes (including Value Added Tax): Taxes that a non-federal entity is required to pay are generally allowable.",
  "200.471": "Telecommunication costs and video surveillance costs: Costs are allowable with conditions regarding reasonable usage.",
  "200.472": "Training and education costs: Costs of training and education are allowable for employee development.",
  "200.473": "Transportation costs: Costs of freight, express, cartage, and postage are allowable.",
  "200.474": "Travel costs: Expenses for transportation, lodging, subsistence, and related items are allowable following entity policy or federal rates.",
  "200.475": "Trustees: Travel and subsistence costs of trustees are allowable.",
  "200.501": "Single audit requirements: Non-federal entities that expend $750,000 or more in federal awards during their fiscal year must have a single or program-specific audit.",
};
