import React from "react";
import { Text, View, StyleSheet } from "@react-pdf/renderer";

const styles = StyleSheet.create({
  section: {
    marginTop: 30,
    padding: 15,
    backgroundColor: "#f8fafc",
    borderWidth: 1,
    borderColor: "#e2e8f0",
    borderRadius: 4,
  },
  title: {
    fontSize: 11,
    fontFamily: "Helvetica-Bold",
    marginBottom: 8,
    color: "#1e293b",
  },
  text: {
    fontSize: 8,
    lineHeight: 1.5,
    color: "#64748b",
  },
});

export function Disclaimer() {
  return (
    <View style={styles.section}>
      <Text style={styles.title}>Disclaimer</Text>
      <Text style={styles.text}>
        This report was generated by GrantLedger using AI-assisted expense categorization.
        While GrantLedger references 2 CFR 200 (Uniform Guidance) cost principles and SF-424A
        budget categories, this report does not constitute legal, accounting, or compliance advice.
      </Text>
      <Text style={[styles.text, { marginTop: 6 }]}>
        All AI-generated categorizations have been reviewed and confirmed by authorized personnel
        as indicated in this report. However, organizations should consult with their independent
        auditor and/or legal counsel to ensure full compliance with applicable federal regulations.
      </Text>
      <Text style={[styles.text, { marginTop: 6 }]}>
        GrantLedger is not responsible for any audit findings, disallowed costs, or compliance
        determinations that may result from the use of this tool. Final responsibility for
        compliance rests with the grant recipient organization.
      </Text>
    </View>
  );
}
